### ISSUE TITLE
add export and import funciton

### ISSUE THREAD

**Issue by TANAKA-Makoto** [firecampapp/fc-support#14]
it would be more helpful if  it support export and import saved requests.

**Comment by Nishchit14** [comment]
Thanks for the feature suggestions @TANAKA-Makoto, We'll release Export/Import functionality in the upcoming release :fire:

**Comment by amtb** [comment]
hi @Nishchit14 
Any update on this ? I guess the next release on which the feature will be included wasn't 0.4.0 right ?

Cheers.

**Comment by Nishchit14** [comment]
yes, @amtb 

Import/Export is under development and will be ready to ship soon. ETA I can estimate is the first week of September. This is a long wait since the last release but next major release will bring so many goodies and most importantly REST client with Realtime workflow.

The first look of the import/export design looks like this...

![image](https://user-images.githubusercontent.com/5078921/63014861-291e9300-bead-11e9-8fb1-c39e1ba8d463.png)

**Comment by amtb** [comment]
cheers mate, let's wait and see.

**Comment by Nishchit14** [comment]
shipped with [v0.6.0](https://github.com/firecampapp/fc-support/releases/tag/v0.6.0) 🚀
